version: "3.8"

services:
  frontend:
    container_name: event-calendar-client
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./frontend/.env:/app/.env
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    container_name: event-calendar-api
    build: ./backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend/src/EventCalendar:/app  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    

  